# Generated by Django 4.2.13 on 2024-09-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.TextField()),
                ('attack_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
            ],
        ),
    ]
