# Generated by Django 4.2.13 on 2024-12-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSWeb', '0002_alter_alert_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
