# Generated by Django 5.1.1 on 2024-10-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSWeb', '0002_alter_alert_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('pattern', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
            ],
        ),
    ]
