# Generated by Django 5.1.1 on 2024-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSWeb', '0005_remove_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='rule_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
