# Generated by Django 5.1.1 on 2024-11-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDSWeb', '0006_alert_rule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='rule_name',
        ),
    ]
