# Generated by Django 5.1.1 on 2024-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSWeb', '0007_remove_alert_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
